### ISSUE TITLE
Security: If use the wrong url, the list of all url format is show up

### ISSUE THREAD

**Issue by ZEZAY** [bleachjade/Kvent#32]
Like this: 

![image](https://user-images.githubusercontent.com/44806732/100895940-ad58b780-34f0-11eb-9698-d40b2edc2dd3.png)

**Comment by bleachjade** [comment]
@ZEZAY I fixed it! Thank you for your suggestion, this one is a hard one for our group because we mess something up in the STATIC templates and didn't know it was wrong

![image](https://user-images.githubusercontent.com/46812243/101869311-b3fec300-3bb1-11eb-862d-1f7e9c77c412.png)

- we are going to make a 404-page error and others later on.
